from __future__ import annotations

from copy import deepcopy

from app.analysis.analyst_profiles import list_analyst_profiles
from app.analysis.valuation_parameter_matrix import RULE_VALUATION_MAPPINGS

CONFIG_SCHEMA_VERSION = "1.0"


def _rule_mappings() -> dict[str, dict[str, object]]:
    mappings: dict[str, dict[str, object]] = {}
    for profile in list_analyst_profiles():
        for rule in profile.rules:
            mapping = RULE_VALUATION_MAPPINGS[(profile.id, rule.id)]
            mappings[f"{profile.id}.{rule.id}"] = {
                "profile_id": profile.id,
                "profile_name": profile.display_name,
                "rule_id": rule.id,
                "rule_label": rule.label,
                "dimensions": dict(mapping.dimensions),
                "calculation_role": mapping.calculation_role,
                "price_blind_compatible": mapping.price_blind_compatible,
            }
    return mappings


_DEFAULT_CONFIG: dict[str, object] = {
    "data_sampling": {
        "company_list_limit": 20,
        "company_list_limit_max": 100,
        "financial_display_periods": 60,
        "analysis_financial_periods": 40,
        "valuation_financial_records": 120,
        "announcement_lookback_years": 1,
        "announcement_retention_limit": 50,
        "announcement_page_size": 50,
        "announcement_max_pages": 200,
        "analysis_announcement_pool": 80,
        "analysis_announcement_items": 20,
        "analysis_evidence_items": 10,
        "external_evidence_limit": 10,
        "external_search_default_results": 5,
        "announcement_model_chars": 12000,
        "announcement_keyword_summary_chars": 120,
        "announcement_head_ratio": 0.70,
        "analysis_excerpt_chars": 360,
        "manual_import_model_chars": 1800,
        "manual_import_snapshot_chars": 3600,
        "evidence_excerpt_chars": 1800,
        "search_snippet_chars": 500,
        "search_title_chars": 160,
        "memo_list_items": 12,
        "price_decision_history_limit": 20,
    },
    "financial_flags": {
        "cagr_years": [3, 5],
        "stability_periods": 5,
        "stability_range": 0.05,
        "trend_change": 0.05,
        "revenue_yoy_min": 0.0,
        "net_profit_yoy_min": 0.0,
        "profit_revenue_gap_min": -0.10,
        "asset_liability_ratio_max": 0.70,
        "ocf_to_revenue_min": 0.05,
        "fcf_to_profit_min": 0.0,
        "investment_profit_ratio_abs_max": 0.20,
        "fair_value_profit_ratio_abs_max": 0.10,
        "impairment_profit_ratio_max": 0.10,
        "non_operating_profit_ratio_abs_max": 0.10,
        "effective_tax_rate_min": 0.0,
        "effective_tax_rate_max": 0.35,
        "deducted_profit_ratio_min": 0.80,
        "margin_decline": 0.05,
        "period_expense_rise": 0.05,
        "finance_expense_rise": 0.03,
    },
    "analyst_engine": {
        "model_temperatures": {
            "announcement": 0.10,
            "evidence_plan": 0.20,
            "evidence_extract": 0.10,
            "analyst": 0.20,
            "memo": 0.20,
        },
        "base_profile_scores": {
            "buffett": 0.68,
            "peter_lynch": 0.62,
            "munger": 0.64,
            "duan_yongping": 0.66,
            "graham": 0.58,
            "fisher": 0.58,
            "lin_yuan": 0.62,
            "li_lu": 0.62,
        },
        "profile_default_score": 0.56,
        "feature_adjustments": {
            "consumer_brand_primary": 0.20,
            "consumer_brand_secondary": 0.10,
            "tech_growth": 0.16,
            "cyclical_macro_defensive": 0.08,
            "asset_heavy_graham": 0.12,
            "cash_flow_quality": 0.06,
        },
        "profile_fit": {
            "industry_weight": 0.55,
            "rule_coverage_weight": 0.30,
            "evidence_support_weight": 0.15,
            "minimum": 0.20,
            "maximum": 0.92,
            "industry_maximum": 0.95,
            "few_financial_periods": 3,
            "few_financial_penalty": 0.08,
            "missing_external_penalty": 0.04,
        },
        "data_confidence": {
            "financial_weight": 0.45,
            "announcement_weight": 0.25,
            "external_weight": 0.20,
            "source_balance_weight": 0.10,
            "minimum": 0.20,
            "maximum": 0.92,
            "accounting_event_penalty": 0.06,
            "financial_present": 0.35,
            "financial_periods_bonus": 0.20,
            "financial_periods_required": 3,
            "latest_period_bonus": 0.15,
            "profitability_bonus": 0.12,
            "cash_flow_bonus": 0.08,
            "financial_gap_penalty_each": 0.03,
            "financial_gap_penalty_cap": 0.25,
            "announcement_count_cap": 0.55,
            "announcement_summary_cap": 0.30,
            "announcement_target_count": 20,
            "accounting_bonus": 0.10,
            "governance_bonus": 0.05,
            "external_present": 0.35,
            "external_analyzed_weight": 0.35,
            "external_source_bonus_each": 0.05,
            "external_source_bonus_cap": 0.20,
            "search_lead_penalty_each": 0.04,
            "search_lead_penalty_cap": 0.25,
        },
        "announcement_ranking": {
            "category_bonus": 0.26,
            "accounting_bonus": 0.24,
            "term_bonus_each": 0.04,
            "term_bonus_cap": 0.22,
            "summary_bonus": 0.06,
        },
        "evidence_ranking": {"credibility_weight": 0.50, "importance_weight": 0.50},
        "source_priority": {
            "regulatory": 0.20,
            "public_data": 0.18,
            "policy": 0.16,
            "web": 0.10,
            "company_news": 0.08,
            "industry_news": 0.06,
        },
        "manual_import_credibility_cap": 0.60,
        "tier_thresholds": {"high": 0.78, "medium": 0.55},
    },
    "valuation_rule_matrix": {
        "status_scores": {
            "pass": 1.0,
            "neutral": 0.0,
            "unknown": -0.1,
            "warn": -0.5,
            "fail": -2.0,
        },
        "safety_margin_additions": {
            "pass": 0.0,
            "neutral": 0.009,
            "unknown": 0.012,
            "warn": 0.016,
            "fail": 0.030,
        },
        "safety_margin_analyst_scale": 8.0,
        "safety_margin_min": 0.1,
        "safety_margin_max": 0.5,
        "confidence_weight": 0.50,
        "profile_fit_weight": 0.50,
        "weight_exponent": 2.0,
        "analyst_score_min": 0.20,
        "analyst_score_max": 1.0,
        "dimension_score_min": -2.0,
        "dimension_score_max": 1.0,
        "rule_mappings": _rule_mappings(),
    },
    "memo_decision": {
        "min_successful_analysts": 2,
        "model_confidence_map": {"low": 0.35, "medium": 0.65, "high": 0.85},
    },
    "valuation_models": {
        "forecast_years": 5,
        "normalization_year_weights": [0.50, 0.30, 0.20],
        "fcf_profit_cap": 1.30,
        "fcf_profit_weak": 0.60,
        "growth_source_priority": [
            "free_cash_flow_cagr_5y",
            "free_cash_flow_cagr_3y",
            "net_profit_cagr_5y",
            "net_profit_cagr_3y",
            "revenue_cagr_5y",
            "revenue_cagr_3y",
        ],
        "default_growth": 0.04,
        "financial_growth_min": -0.05,
        "financial_growth_max": 0.12,
        "base_discount_rate": 0.095,
        "flag_discount_penalty": 0.005,
        "gap_discount_penalty": 0.003,
        "discount_penalty_cap": 0.025,
        "financial_discount_min": 0.08,
        "financial_discount_max": 0.14,
        "base_terminal_growth": 0.02,
        "discount_terminal_gap": 0.01,
        "analyst_impact_scale": 2.0,
        "gap_penalties": {"high": 0.25, "medium": 0.12, "low": 0.05, "pack": 0.04},
        "gap_penalty_cap": 1.0,
        "composite_weights": {
            "quality": {
                "business_quality": 0.30,
                "moat_durability": 0.25,
                "cash_flow_reliability": 0.20,
                "management_quality": 0.15,
                "pricing_power": 0.10,
            },
            "growth": {
                "growth_runway": 0.40,
                "pricing_power": 0.25,
                "demand_durability": 0.20,
                "execution_quality": 0.15,
                "capital_intensity_penalty": 0.15,
            },
            "risk": {
                "balance_sheet_risk": 0.25,
                "permanent_loss_risk": 0.25,
                "cyclicality": 0.20,
                "accounting_quality": 0.15,
                "data_gap_penalty": 0.15,
            },
        },
        "parameter_deltas": {
            "growth_growth": 0.030,
            "growth_quality": 0.012,
            "growth_risk": -0.020,
            "owner_growth_growth": 0.020,
            "owner_growth_quality": 0.018,
            "owner_growth_capital": -0.025,
            "owner_growth_risk": -0.018,
            "discount_quality": -0.018,
            "discount_risk": 0.030,
            "discount_disagreement": 0.012,
            "terminal_moat": 0.012,
            "terminal_pricing": 0.006,
            "terminal_risk": -0.014,
            "spread_risk": 0.020,
            "spread_disagreement": 0.012,
            "spread_unknown": 0.012,
        },
        "scenario_spread_base": 0.020,
        "scenario_spread_min": 0.015,
        "scenario_spread_max": 0.080,
        "base_bounds": {
            "growth": [-0.08, 0.16],
            "owner_growth": [-0.08, 0.15],
            "discount": [0.075, 0.16],
            "terminal": [0.0, 0.035],
        },
        "scenarios": {
            "conservative": {
                "growth_spread": -1.0,
                "owner_growth_spread": -1.0,
                "discount_spread": 0.60,
                "terminal_spread": -0.30,
                "growth_bounds": [-0.10, 0.10],
                "owner_growth_bounds": [-0.10, 0.10],
                "discount_bounds": [0.09, 0.18],
                "terminal_bounds": [0.0, 0.035],
            },
            "base": {},
            "optimistic": {
                "growth_spread": 1.0,
                "owner_growth_spread": 1.0,
                "discount_spread": -0.35,
                "terminal_spread": 0.25,
                "growth_bounds": [-0.02, 0.18],
                "owner_growth_bounds": [-0.02, 0.16],
                "discount_bounds": [0.075, 0.14],
                "terminal_bounds": [0.0, 0.035],
            },
        },
        "permanent_loss_optimistic_cap": 0.50,
        "model_weights": {
            "owner_earnings": 0.35,
            "dcf": 0.35,
            "residual_income": 0.15,
            "dividend_discount": 0.10,
            "asset_value": 0.05,
        },
        "model_weight_tolerance": 0.000001,
        "non_cash_asset_haircuts": {"conservative": 0.60, "base": 0.80, "optimistic": 1.00},
        "equity_fallback_haircuts": {"conservative": 0.80, "base": 1.00, "optimistic": 1.10},
        "dispersion_ratio": 1.35,
        "confidence": {
            "base": 0.78,
            "high_gap_penalty": 0.16,
            "medium_gap_penalty": 0.06,
            "low_gap_penalty": 0.03,
            "skipped_method_penalty": 0.12,
            "dispersion_penalty": 0.08,
            "minimum": 0.10,
            "maximum": 0.90,
            "high_threshold": 0.72,
            "medium_threshold": 0.45,
        },
        "sensitivity": {"growth_step": 0.02, "discount_step": 0.01},
    },
    "price_decision": {
        "safety_margin_min": 0.1,
        "safety_margin_max": 0.5,
        "buy_price_scenario": "base",
    },
}


def default_parameter_config() -> dict[str, object]:
    return deepcopy(_DEFAULT_CONFIG)
